/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserType = IDL.Variant({
  'landlord' : IDL.Null,
  'tenant' : IDL.Null,
});
export const EarlyAccessSignup = IDL.Record({
  'userType' : UserType,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'numberOfProperties' : IDL.Nat,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSignups' : IDL.Func([], [IDL.Vec(EarlyAccessSignup)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSignupCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitEarlyAccessSignup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserType, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserType = IDL.Variant({ 'landlord' : IDL.Null, 'tenant' : IDL.Null });
  const EarlyAccessSignup = IDL.Record({
    'userType' : UserType,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'numberOfProperties' : IDL.Nat,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSignups' : IDL.Func([], [IDL.Vec(EarlyAccessSignup)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSignupCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitEarlyAccessSignup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserType, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };